exercism/mips

- config.json
- exercises/isogram/example.mips
- exercises/isogram/runner.mips
- exercises/triangle/example.mips
- exercises/triangle/runner.mips
Adds two more exercises. No need for review, just FYI @quackingduck
> Add isogram and triangle

- config.json
- exercises/raindrops/example.mips
- exercises/raindrops/runner.mips
- exercises/rna-transcription/example.mips
- exercises/rna-transcription/runner.mips
@quackingduck mind taking a look?
This PR adds a couple of exercises (raindrops and rna-transcription) to demonstrate testing of functions returning a string.
It also demonstrates how hard some of these APIs are to satisfy in asm... did not think the raindrops solution would require so many instructions!
> Problems returning pointer to string

- bin/test
- exercises/rna-transcription/runner.mips
No need for review, fixes register confusion in test runner. Will merge when CI clears.
> Fix register mixup in rna transcription runner

- config.json
This will let the website display the runner as the test file.
Fixes #16
> Add the test pattern to config.json

- config/exercise_readme.go.tmpl
- exercises/atbash-cipher/README.md
- exercises/binary/README.md
- exercises/difference-of-squares/README.md
- exercises/hamming/README.md
- exercises/hexadecimal/README.md
- exercises/isogram/README.md
- exercises/leap/README.md
- exercises/nth-prime/README.md
- exercises/octal/README.md
- exercises/raindrops/README.md
- exercises/rna-transcription/README.md
- exercises/scrabble-score/README.md
- exercises/triangle/README.md
- exercises/trinary/README.md
We are working towards making exercises stand-alone. That is to say: no more generating READMEs on the fly.
This will give maintainers more control over each individual exercise README, and it will also make some of the backend logic for delivering exercises simpler.
The README template uses the Go text/template package, and the default templates generate the same READMEs as we have been generating on the fly.  See the documentation in [regenerating exercise readmes][regenerate-docs] for details.
The READMEs can be generated at any time using a new 'generate' command in configlet. This command has not yet landed in master or been released, but can be built from source in the generate-readmes branch on [configlet][].
[configlet]: https://github.com/exercism/configlet
[regenerate-docs]: …
> Generate static exercise README templates

- exercises/triangle/runner.mips
- Before this case, it was possible to pass all tests by checking sides
1/3 and 2/3. This case forces the check for sides 1/2 for isosceles
> Add isosceles test case to check first two sides

- exercises/practice/atbash-cipher/.meta/config.json
- exercises/practice/binary/.meta/config.json
- exercises/practice/difference-of-squares/.meta/config.json
- exercises/practice/hamming/.meta/config.json
- exercises/practice/hexadecimal/.meta/config.json
- exercises/practice/isogram/.meta/config.json
- exercises/practice/leap/.meta/config.json
- exercises/practice/nth-prime/.meta/config.json
- exercises/practice/octal/.meta/config.json
- exercises/practice/raindrops/.meta/config.json
- exercises/practice/rna-transcription/.meta/config.json
- exercises/practice/scrabble-score/.meta/config.json
- exercises/practice/triangle/.meta/config.json
- exercises/practice/trinary/.meta/config.json
To help tracks define the files in the exercise's `.meta/config.json` file, we've added support for defining these file patterns in the track's `config.json` file. See [this PR](https://github.com/exercism/docs/pull/58).
This PR updates the file paths defined in the `files` property of each exercise's `.meta/config.json` file according to the file patterns defined in the track's `config.json` file.
We only update a file path in the `.meta/config.json` file if:
- The file path pattern is a non-empty array in the `config.json` file
- The file path pattern is either not set or an empty array in the `.meta/config.json` file
This means that exercises that had already defined files in the `.meta/config.json` won't be touched in this PR.
Note that this PR is just an easy way for tracks to …
> 🤖 Sync exercise files keys based on file path patterns

- config.json
- exercises/practice/hello-world/.docs/instructions.md
- exercises/practice/hello-world/.meta/config.json
- exercises/practice/hello-world/example.mips
- exercises/practice/hello-world/runner.mips
@ErikSchierboom Could you verify this?
Ref: #90
> Add hello-world exercise

- exercises/practice/atbash-cipher/.docs/instructions.md
- exercises/practice/binary/.docs/instructions.md
- exercises/practice/difference-of-squares/.docs/instructions.md
- exercises/practice/hamming/.docs/instructions.md
- exercises/practice/hello-world/.docs/instructions.md
- exercises/practice/hexadecimal/.docs/instructions.md
- exercises/practice/isogram/.docs/instructions.md
- exercises/practice/leap/.docs/instructions.md
- exercises/practice/nth-prime/.docs/instructions.md
- exercises/practice/octal/.docs/instructions.md
- exercises/practice/raindrops/.docs/instructions.md
- exercises/practice/rna-transcription/.docs/instructions.md
- exercises/practice/triangle/.docs/instructions.md
- exercises/practice/trinary/.docs/instructions.md
This brings in recent improvements to the docs for all practice exercises.
> Sync docs with problem-specifications

- exercises/practice/atbash-cipher/.meta/config.json
- exercises/practice/binary/.meta/config.json
- exercises/practice/difference-of-squares/.meta/config.json
- exercises/practice/hamming/.meta/config.json
- exercises/practice/hello-world/.meta/config.json
- exercises/practice/hexadecimal/.meta/config.json
- exercises/practice/isogram/.meta/config.json
- exercises/practice/leap/.meta/config.json
- exercises/practice/nth-prime/.meta/config.json
- exercises/practice/octal/.meta/config.json
- exercises/practice/raindrops/.meta/config.json
- exercises/practice/rna-transcription/.meta/config.json
- exercises/practice/scrabble-score/.meta/config.json
- exercises/practice/triangle/.meta/config.json
- exercises/practice/trinary/.meta/config.json
This runs the `bin/configlet fmt --update` command to
reformat the exercise configs.
> Reformat exercise config files

- config.json
Tried to be factual, and avoid hyperbolae, so accessed the following references:
- [Mips Architecture Overview](https://tams.informatik.uni-hamburg.de/applets/hades/webdemos/mips.html)
- [MIPS Architectuers](https://www.mips.com/products/architectures/)
- [MIPS architecture](https://en.wikipedia.org/wiki/MIPS_architecture)
- [Computer Architecture](https://shop.elsevier.com/books/computer-architecture/hennessy/978-0-12-811905-1)
- [Open Sourcing MIPS](https://www.hackster.io/news/what-does-the-open-sourcing-of-mips-mean-for-risc-v-and-the-rest-of-us-5f253ed4c361)
> [Track]: Add key features and icons

- config.json
Closes https://github.com/exercism/mips/issues/71
> Fix indent size

- exercises/practice/resistor-color-duo/.docs/instructions.append.md
- exercises/practice/resistor-color-duo/impl.mips
- exercises/practice/resistor-color/.docs/instructions.append.md
- exercises/practice/resistor-color/impl.mips
- exercises/practice/scrabble-score/.docs/instructions.append.md
- exercises/practice/scrabble-score/impl.mips
Fixed the the wrong assignment for the register $v0 on the exercises:
Registor Color
Registor Color Duo
Scrabble Score
> Fix wrong register assignment

- config.json
- exercises/practice/darts/.docs/hints.md
- exercises/practice/darts/.docs/instructions.append.md
- exercises/practice/darts/.docs/instructions.md
- exercises/practice/darts/.meta/config.json
- exercises/practice/darts/.meta/example.mips
- exercises/practice/darts/.meta/tests.toml
- exercises/practice/darts/impl.mips
- exercises/practice/darts/runner.mips
We use integer coordinates, as some MIPS resources do not cover floating point instructions.
> Add darts exercise

- config.json
- exercises/practice/collatz-conjecture/.docs/hints.md
- exercises/practice/collatz-conjecture/.docs/instructions.append.md
- exercises/practice/collatz-conjecture/.docs/instructions.md
- exercises/practice/collatz-conjecture/.meta/config.json
- exercises/practice/collatz-conjecture/.meta/example.mips
- exercises/practice/collatz-conjecture/.meta/tests.toml
- exercises/practice/collatz-conjecture/impl.mips
- exercises/practice/collatz-conjecture/runner.mips
Adapted from 2018 PR
https://github.com/exercism/mips/pull/46
> Add collatz-conjecture exercise

- config.json
We declare the following exercises as foregone:
- bank-account
- parallel-letter-frequency
> Forego concurrency exercises

- config.json
- exercises/practice/secret-handshake/.docs/hints.md
- exercises/practice/secret-handshake/.docs/instructions.append.md
- exercises/practice/secret-handshake/.docs/instructions.md
- exercises/practice/secret-handshake/.docs/introduction.md
- exercises/practice/secret-handshake/.meta/config.json
- exercises/practice/secret-handshake/.meta/example.mips
- exercises/practice/secret-handshake/.meta/tests.toml
- exercises/practice/secret-handshake/impl.mips
- exercises/practice/secret-handshake/runner.mips
> Add secret-handshake exercise

- docs/RESOURCES.md
MIPS Instruction Reference
https://mathcs.holycross.edu/~csci226/MIPS/MIPS_InstructionReference.html
MIPS Instruction Set Cheat Sheet
https://group.miletic.net/en/teaching/materials/mips-instruction-set/
Writing and Using Macros
https://courses.missouristate.edu/kenvollmar/mars/help/MacrosHelp.html
resolves #222
> Add resource links

- config.json
- binary
- trinary
- octal
- hexadecimal
> Deprecate exercises

- config.json
- exercises/practice/square-root/.meta/config.json
Requested in [forum](http://forum.exercism.org/t/mips-pythagorean-triplet-o-n-2-isnt-enough-to-pass-test/12028)
> Increase pythagorean-triplet difficulty

- exercises/practice/darts/.docs/instructions.md
- exercises/practice/darts/.meta/config.json
- exercises/practice/hello-world/.meta/config.json
- exercises/practice/matching-brackets/.docs/instructions.md
- exercises/practice/matching-brackets/.docs/introduction.md
- exercises/practice/pig-latin/.docs/instructions.md
- exercises/practice/protein-translation/.meta/tests.toml
- exercises/practice/protein-translation/runner.mips
- exercises/practice/raindrops/.meta/config.json
- exercises/practice/resistor-color-duo/.docs/instructions.md
- exercises/practice/roman-numerals/.meta/tests.toml
- exercises/practice/roman-numerals/runner.mips
> Sync exercises

- exercises/practice/triangle/.meta/tests.toml
- exercises/practice/triangle/runner.mips
tests.toml is now consistent with the number of test cases run.
[no important files changed]
> Sync triangle tests
